package chat.impl;

//==============================================================================
import java.awt.Color;

public class PrivatePanel extends javax.swing.JPanel {

    private String nick;

    private ChatFrame frame;

    //============================================================================
    /**
     * Crea una nuova istanza di PrivatePanel
     */
    public PrivatePanel(String nick, ChatFrame frame) {
        this.nick = nick;
        this.frame = frame;
        initComponents();
        jLabel2.setText(nick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jButton3 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jPanel2 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();

    setBackground(new java.awt.Color(51, 153, 0));
    setMinimumSize(new java.awt.Dimension(500, 400));
    setPreferredSize(new java.awt.Dimension(500, 400));
    setLayout(new java.awt.BorderLayout());

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 204, 0))); // NOI18N
    jPanel3.setMinimumSize(new java.awt.Dimension(500, 100));
    jPanel3.setOpaque(false);
    jPanel3.setPreferredSize(new java.awt.Dimension(500, 100));
    jPanel3.setLayout(new java.awt.BorderLayout());

    jPanel4.setMinimumSize(new java.awt.Dimension(100, 33));
    jPanel4.setOpaque(false);
    jPanel4.setPreferredSize(new java.awt.Dimension(100, 33));

    jButton3.setText("Clear");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearHistory(evt);
      }
    });
    jPanel4.add(jButton3);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
    jLabel1.setForeground(new java.awt.Color(255, 204, 0));
    jLabel1.setText("Session with:");
    jPanel4.add(jLabel1);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
    jLabel2.setForeground(new java.awt.Color(255, 204, 0));
    jLabel2.setText("Agent");
    jPanel4.add(jLabel2);

    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closePanel(evt);
      }
    });
    jPanel4.add(jButton1);

    jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
    jScrollPane1.setOpaque(false);
    jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setMinimumSize(new java.awt.Dimension(104, 22));
    jScrollPane1.setViewportView(jTextArea1);

    jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    add(jPanel3, java.awt.BorderLayout.CENTER);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 204, 0))); // NOI18N
    jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
    jPanel1.setOpaque(false);
    jPanel1.setPreferredSize(new java.awt.Dimension(100, 140));
    jPanel1.setVerifyInputWhenFocusTarget(false);
    jPanel1.setLayout(new java.awt.BorderLayout());

    jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));
    jScrollPane2.setOpaque(false);
    jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));
    jScrollPane2.setRequestFocusEnabled(false);

    jTextArea2.setColumns(20);
    jTextArea2.setLineWrap(true);
    jTextArea2.setRows(5);
    jTextArea2.setMinimumSize(new java.awt.Dimension(104, 22));
    jTextArea2.setPreferredSize(new java.awt.Dimension(164, 194));
    jScrollPane2.setViewportView(jTextArea2);

    jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jPanel2.setMinimumSize(new java.awt.Dimension(77, 33));
    jPanel2.setOpaque(false);
    jPanel2.setPreferredSize(new java.awt.Dimension(77, 33));
    jPanel2.setVerifyInputWhenFocusTarget(false);

    jButton2.setText("Send");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendMessage(evt);
      }
    });
    jPanel2.add(jButton2);

    jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

    add(jPanel1, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void sendMessage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessage
// TODO add your handling code here:
      jTextArea1.append("<---->");
      jTextArea1.append(jTextArea2.getText());
      jTextArea1.append("\n");
      frame.sendMessage(this.nick, jTextArea2.getText());
      jTextArea2.setText(null);
  }//GEN-LAST:event_sendMessage

  private void clearHistory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearHistory
// TODO add your handling code here:
      jTextArea1.setText(null);
  }//GEN-LAST:event_clearHistory

  private void closePanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closePanel
// TODO add your handling code here:
      frame.closePanel(this);
  }//GEN-LAST:event_closePanel


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  // End of variables declaration//GEN-END:variables

    //============================================================================
    void appendMessage(String nick, String message) {
        if (message != null) {
            if (message.startsWith("[OFFLINE]")) {
                jTextArea1.setBackground(Color.lightGray);
            }
            jTextArea1.append("<" + nick + "> ");
            jTextArea1.append(message);
            jTextArea1.append("\n");
        }
    }
}
