 package chat.impl;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;

public class PublicPanel extends javax.swing.JPanel {
  
  private final int SCANNER_SLEEP = 5000;
  
  private ChatFrame frame;
  
  //============================================================================
  /** Gestisce la notifica dei nick e la rimanda al tablemodel. */
  void peerAdvertise (String user) {
    NickListModel lm = (NickListModel) jList1.getModel();
    lm.addNick(user);
  }
  
  //============================================================================
  /** Crea una nuova istanza di PublicPanel */
  public PublicPanel(final ChatFrame frame) {
    this.frame = frame;
    initComponents();
    jList1.setModel(new NickListModel());
    jList1.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
          if (e.getClickCount() == 2) {
            String nick = (String) jList1.getModel().getElementAt(jList1.locationToIndex(e.getPoint()));
            frame.appendMessage(true, nick, null);
          }
        }});
    new ScannerThread().start();
  }
  
  //============================================================================
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel11 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jPanel12 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jPanel13 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jPanel14 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jButton7 = new javax.swing.JButton();

    setBackground(new java.awt.Color(0, 153, 153));
    setForeground(new java.awt.Color(0, 153, 153));
    setMinimumSize(new java.awt.Dimension(500, 400));
    setPreferredSize(new java.awt.Dimension(500, 400));
    setLayout(new java.awt.BorderLayout());

    jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 204, 204))); // NOI18N
    jPanel11.setMaximumSize(new java.awt.Dimension(100, 50));
    jPanel11.setMinimumSize(new java.awt.Dimension(50, 50));
    jPanel11.setOpaque(false);
    jPanel11.setPreferredSize(new java.awt.Dimension(100, 87));
    jPanel11.setLayout(new java.awt.BorderLayout());

    jScrollPane3.setBackground(new java.awt.Color(255, 51, 51));
    jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane3.setOpaque(false);

    jList1.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList1.setDoubleBuffered(true);
    jScrollPane3.setViewportView(jList1);

    jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

    jPanel3.setOpaque(false);
    jPanel3.setPreferredSize(new java.awt.Dimension(100, 33));
    jPanel3.setRequestFocusEnabled(false);

    jButton1.setText("Update");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doUpdateUsers(evt);
      }
    });
    jPanel3.add(jButton1);

    jPanel11.add(jPanel3, java.awt.BorderLayout.SOUTH);

    add(jPanel11, java.awt.BorderLayout.WEST);

    jPanel12.setOpaque(false);
    jPanel12.setLayout(new java.awt.BorderLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 204, 204))); // NOI18N
    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel2.setOpaque(false);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
    jLabel3.setForeground(new java.awt.Color(255, 204, 204));
    jLabel3.setText("Public Session");
    jPanel2.add(jLabel3);

    jButton2.setText("Clear");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearHistory(evt);
      }
    });
    jPanel2.add(jButton2);

    jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

    jTextArea1.setColumns(20);
    jTextArea1.setEditable(false);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel12.add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 204, 204))); // NOI18N
    jPanel13.setOpaque(false);
    jPanel13.setLayout(new java.awt.BorderLayout());

    jTextArea2.setColumns(20);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jPanel14.setOpaque(false);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
    jLabel2.setForeground(new java.awt.Color(255, 204, 204));
    jLabel2.setText("Agent");
    jPanel14.add(jLabel2);

    jButton7.setText("Send");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendMessage(evt);
      }
    });
    jPanel14.add(jButton7);

    jPanel13.add(jPanel14, java.awt.BorderLayout.SOUTH);

    jPanel12.add(jPanel13, java.awt.BorderLayout.SOUTH);

    add(jPanel12, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void sendMessage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessage
// TODO add your handling code here:
    jTextArea1.append("<---->");
    jTextArea1.append(jTextArea2.getText());
    jTextArea1.append("\n");
    frame.sendMessage(null, jTextArea2.getText()); 
    jTextArea2.setText(null);
  }//GEN-LAST:event_sendMessage

  private void clearHistory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearHistory
// TODO add your handling code here:
    jTextArea1.setText(null);
  }//GEN-LAST:event_clearHistory

  private void doUpdateUsers(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doUpdateUsers
  // TODO add your handling code here:
    frame.doUpdateUsers();    
  }//GEN-LAST:event_doUpdateUsers
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton7;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JList jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel11;
  private javax.swing.JPanel jPanel12;
  private javax.swing.JPanel jPanel13;
  private javax.swing.JPanel jPanel14;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  // End of variables declaration//GEN-END:variables
  
  
//============================================================================
  void setMyNick (String nick){
    jLabel2.setText(nick);
  }
  
  //============================================================================
  void appendMessage(String nick, String message) {
    jTextArea1.append("<"+nick+"> ");
    jTextArea1.append(message);
    jTextArea1.append("\n");
  }

 //============================================================================
  /** Invia periodicamente un messaggio di keep-alive, e purga i peer che non
   *        rispondono per un certo numero di volte.
   */
  private class ScannerThread extends Thread {
    public void run () {
      while (true){
        try { sleep(SCANNER_SLEEP); }
        catch (Exception ex){}
        ((NickListModel)jList1.getModel()).purgeNicks(new Date().getTime() - 2 * SCANNER_SLEEP);
          System.out.println("Scanner thread cycle "+frame.getAgent().getId());
        doUpdateUsers(null);
      }
    }
  }

}
